site_name: python-packaging-best-practices
site_url: https://github.com/capjamesg/python-packaging-best-practices
site_author: capjamesg
site_description: Best practices for packaging and documenting Python packages âœ¨
repo_name: capjamesg/python-packaging-best-practices
repo_url: https://github.com/capjamesg/python-packaging-best-practices
edit_uri: https://github.com/capjamesg/python-packaging-best-practices/tree/main/docs
copyright: CC-BY-NC-SA-4.0

extra_css:
  - stylesheets/styles.css

nav:
  - Introduction ğŸ‘‹: index.md
  - READMEs ğŸ“„: readmes.md
  - Project and Code Documentation ğŸ“š: code-docs.md
  - Linting ğŸ–Œï¸: linting.md
  - Versioning ğŸ—„ï¸: versioning.md
  - Release Notes âœï¸: release-notes.md
  - Continuous Integration ğŸ§ª: ci.md
  - Conclusion: conclusion.md
  - Contributing ğŸ› ï¸: contributing.md

theme:
  name: 'material'
  palette:
    # Palette for light mode
    - scheme: default
      primary: 'custom'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true